[package]
name = "inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
semver = {version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
thiserror = "1"
toml = "0.8"

[dev-dependencies]
serde_test = "1"
