[package]
name = "inventory-cli"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
semver = "1"
inventory = { path = "../inventory", features = ["semver"] }
